// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSearcher.DataAccess.Context;

namespace WebSearcher.DataAccess.Migrations
{
    [DbContext(typeof(WebPageConnectionsContext))]
    partial class WebPageConnectionsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebSearcher.Entities.WebPageConnections", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("WebPageFromId");

                    b.Property<int>("WebPageToId");

                    b.Property<string>("WebPageToUrl");

                    b.HasKey("Id");

                    b.ToTable("WebPageConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
